drop table if exists public."tmp_ceis";

CREATE TABLE public."tmp_ceis" (
	"TIPO_DE_PESSOA" varchar(1) NULL,
	"CPF_OU_CNPJ_DO_SANCIONADO" varchar(1024) NULL,
	"NOME_INFORMADO_PELO_ORGAO_SANCIONADOR" varchar(1024) NULL,
	"RAZAO_SOCIAL_CADASTRO_RECEITA" varchar(1024) NULL,
	"NOME_FANTASIA_CADASTRO_RECEITA" varchar(1024) NULL,
	"NUMERO_DO_PROCESSO" varchar(1024) NULL,
	"TIPO_SANCAO" varchar(1024) NULL,
	"DATA_INICIO_SANCAO" varchar(10) NULL,
	"DATA_FINAL_SANCAO" varchar(10) NULL,
	"ORGAO_SANCIONADOR" varchar(1024) NULL,
	"UF_ORGAO_SANCIONADOR" varchar(2) NULL,
	"ORIGEM_INFORMACOES" varchar(1024) NULL,
	"DATA_ORIGEM_INFORMACOES" varchar(10) NULL,
	"DATA_PUBLICACAO" varchar(10) NULL,
	"PUBLICACAO" varchar(1024) NULL,
	"DETALHAMENTO" varchar(2000) NULL,
	"ABRAGENCIA_DEFINIDA_EM_DECISAO_JUDICIAL" varchar(1024) NULL,
	"FUNDAMENTACAO_LEGAL" varchar(2000) NULL,
	"DESCRICAO_DA_FUNDAMENTACAO_LEGAL" varchar(2500) NULL,
	"DATA_DO_TRANSITO_EM_JULGADO" varchar(10) NULL,
	"COMPLEMENTO_DO_ORGAO" varchar(2000) NULL,
	"OBSERVACOES" varchar(2500) NULL
);

drop table if exists public."final_ceis";


CREATE TABLE public."final_ceis" (
	"TIPO_DE_PESSOA" varchar(1) NULL,
	"CPF_OU_CNPJ_DO_SANCIONADO" varchar(1024) NULL,
	"NOME_INFORMADO_PELO_ORGAO_SANCIONADOR" varchar(1024) NULL,
	"RAZAO_SOCIAL_CADASTRO_RECEITA" varchar(1024) NULL,
	"NOME_FANTASIA_CADASTRO_RECEITA" varchar(1024) NULL,
	"NUMERO_DO_PROCESSO" varchar(1024) NULL,
	"TIPO_SANCAO" varchar(1024) NULL,
	"DATA_INICIO_SANCAO" date  NULL,
	"DATA_FINAL_SANCAO" date NULL,
	"ORGAO_SANCIONADOR" varchar(1024) NULL,
	"UF_ORGAO_SANCIONADOR" varchar(2) NULL,
	"ORIGEM_INFORMACOES" varchar(1024) NULL,
	"DATA_ORIGEM_INFORMACOES" date NULL,
	"DATA_PUBLICACAO" date NULL,
	"PUBLICACAO" varchar(1024) NULL,
	"DETALHAMENTO" varchar(2000) NULL,
	"ABRAGENCIA_DEFINIDA_EM_DECISAO_JUDICIAL" varchar(1024) NULL,
	"FUNDAMENTACAO_LEGAL" varchar(2000) NULL,
	"DESCRICAO_DA_FUNDAMENTACAO_LEGAL" varchar(2500) NULL,
	"DATA_DO_TRANSITO_EM_JULGADO" date NULL,
	"COMPLEMENTO_DO_ORGAO" varchar(2000) NULL,
	"OBSERVACOES" varchar(2500) NULL
);

copy public."tmp_ceis"
from '/home/jose/Downloads/20220301_CEIS.csv'
with 
	delimiter ';'
	csv
	header
	encoding 'latin1';


insert into public."final_ceis"(
	"TIPO_DE_PESSOA",
	"CPF_OU_CNPJ_DO_SANCIONADO",
	"NOME_INFORMADO_PELO_ORGAO_SANCIONADOR",
	"RAZAO_SOCIAL_CADASTRO_RECEITA",
	"NOME_FANTASIA_CADASTRO_RECEITA",
	"NUMERO_DO_PROCESSO",
	"TIPO_SANCAO",
	"DATA_INICIO_SANCAO",
	"DATA_FINAL_SANCAO",
	"ORGAO_SANCIONADOR",
	"UF_ORGAO_SANCIONADOR",
	"ORIGEM_INFORMACOES",
	"DATA_ORIGEM_INFORMACOES",
	"DATA_PUBLICACAO",
	"PUBLICACAO",
	"DETALHAMENTO",
	"ABRAGENCIA_DEFINIDA_EM_DECISAO_JUDICIAL",
	"FUNDAMENTACAO_LEGAL",
	"DESCRICAO_DA_FUNDAMENTACAO_LEGAL",
	"DATA_DO_TRANSITO_EM_JULGADO",
	"COMPLEMENTO_DO_ORGAO",
	"OBSERVACOES"
)
select 
	"TIPO_DE_PESSOA",
	"CPF_OU_CNPJ_DO_SANCIONADO",
	"NOME_INFORMADO_PELO_ORGAO_SANCIONADOR",
	"RAZAO_SOCIAL_CADASTRO_RECEITA",
	"NOME_FANTASIA_CADASTRO_RECEITA",
	"NUMERO_DO_PROCESSO",
	"TIPO_SANCAO",
	to_date("DATA_INICIO_SANCAO", 'DD/MM/YYYY'),
	to_date("DATA_FINAL_SANCAO", 'DD/MM/YYYY'),
	"ORGAO_SANCIONADOR",
	"UF_ORGAO_SANCIONADOR",
	"ORIGEM_INFORMACOES",
	to_date("DATA_ORIGEM_INFORMACOES", 'DD/MM/YYYY'),
	to_date("DATA_PUBLICACAO", 'DD/MM/YYYY'),
	"PUBLICACAO",
	"DETALHAMENTO",
	"ABRAGENCIA_DEFINIDA_EM_DECISAO_JUDICIAL",
	"FUNDAMENTACAO_LEGAL",
	"DESCRICAO_DA_FUNDAMENTACAO_LEGAL",
	to_date("DATA_DO_TRANSITO_EM_JULGADO", 'DD/MM/YYYY'),
	"COMPLEMENTO_DO_ORGAO",
	"OBSERVACOES"
	from public."tmp_ceis";

select * from public."final_ceis";

select fceis."NOME_INFORMADO_PELO_ORGAO_SANCIONADOR"
from public."final_ceis" fceis
inner join final_cpgf fcpgf
on fceis."CPF_OU_CNPJ_DO_SANCIONADO" = fcpgf.documento_favorecido
group by fceis."NOME_INFORMADO_PELO_ORGAO_SANCIONADOR";

select fceis."NOME_INFORMADO_PELO_ORGAO_SANCIONADOR"
from public."final_ceis" fceis
where exists(
	select fcpgf.documento_favorecido
	from final_cpgf fcpgf
	where fcpgf.documento_favorecido = fceis."CPF_OU_CNPJ_DO_SANCIONADO"
);

