drop table if exists tmp_servidores_siape_remuneracao;

create table public."tmp_servidores_siape_remuneracao"(
	"ANO" varchar(1024) null,
	"MES" varchar(1024) null,
	"ID_SERVIDOR_PORTAL" varchar(1024) null,
	"CPF" varchar(1024) null,
	"NOME" varchar(1024) null,
	"REMUNERACAO_BASICA_BRUTA_(R$)" varchar(1024) null,
	"REMUNERACAO_BASICA_BRUTA_(U$)" varchar(1024) null,
	"ABATE-TETO_(R$)" varchar(1024) null,
	"ABATE-TETO_(U$)" varchar(1024) null,
	"GRATIFICACAO_NATALINA_(R$)" varchar(1024) null,
	"GRATIFICACAO_NATALINA_(U$)" varchar(1024) null,
	"ABATE-TETO_(U$)_DA_GRATIFICACAO_NATALINA_(R$)" varchar(1024) null,
	"ABATE-TETO_(U$)_DA_GRATIFICACAO_NATALINA_(U$)" varchar(1024) null,
	"FERIAS_(R$)" varchar(1024) null,
	"FERIAS_(U$)" varchar(1024) null,
	"OUTRAS_REMUNERACOES_EVENTUAIS_(R$)" varchar(1024) null,
	"OUTRAS_REMUNERACOES_EVENTUAIS_(U$)" varchar(1024) null,
	"IRRF_(R$)" varchar(1024) null,
	"IRRF_(U$)" varchar(1024) null,
	"PSS/RPGS_(R$)" varchar(1024) null,
	"PSS/RPGS_(U$)" varchar(1024) null,
	"DEMAIS_DEDUCOES_(R$)" varchar(1024) null,
	"DEMAIS_DEDUCOES_(U$)" varchar(1024) null,
	"PENSAO_MILITAR_(R$)" varchar(1024) null,
	"PENSAO_MILITAR_(U$)" varchar(1024) null,
	"FUNDO_DE_SAUDE_(R$)" varchar(1024) null,
	"FUNDO_DE_SAUDE_(U$)" varchar(1024) null,
	"TAXA_DE_OCUPACAO_IMOVEL_FUNCIONAL_(R$)" varchar(1024) null,
	"TAXA_DE_OCUPACAO_IMOVEL_FUNCIONAL_(U$)" varchar(1024) null,
	"REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_(R$)" varchar(1024) null,
	"REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_(U$)" varchar(1024) null,
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_CIVIL_(R$)(*)" varchar(1024) null,
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_CIVIL_(U$)(*)" varchar(1024) null,
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_MILITAR_(R$)(*)" varchar(1024) null,
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_MILITAR_(U$)(*)" varchar(1024) null,
	"VERBAS_INDENIZATORIAS_P_DESLIGAMENTO_VOLUNTARIO_MP_792/2017_(R$)" varchar(1024) null,
	"VERBAS_INDENIZATORIAS_P_DESLIGAMENTO_VOLUNTARIO_MP_792/2017_(U$)" varchar(1024) null,
	"TOTAL_DE_VERBAS_INDENIZATORIAS_(R$)(*)" varchar(1024) null,
	"TOTAL_DE_VERBAS_INDENIZATORIAS_(U$)(*)" varchar(1024) null
);

copy public."tmp_servidores_siape_remuneracao"
from '/home/jose/Desktop/scripts/files_servidores/servidores_SIAPE/202101_Remuneracao.csv'
with 
	delimiter ';'
	csv
	header
	encoding 'latin1';


delete from tmp_servidores_siape_remuneracao
where "ANO" like '%(*)%';


drop table public."final_servidores_siape_remuneracao";
	
create table public."final_servidores_siape_remuneracao"(
	"ANO" integer null,
	"MES" integer null,
	"ID_SERVIDOR_PORTAL" varchar(1024) null,
	"CPF" varchar(1024) null,
	"NOME" varchar(1024) null,
	"REMUNERACAO_BASICA_BRUTA_(R$)" decimal(20,2) null,
	"REMUNERACAO_BASICA_BRUTA_(U$)" decimal(20,2) null,
	"ABATE-TETO_(R$)" decimal(20,2) null,
	"ABATE-TETO_(U$)" decimal(20,2) null,
	"GRATIFICACAO_NATALINA_(R$)" decimal(20,2) null,
	"GRATIFICACAO_NATALINA_(U$)" decimal(20,2) null,
	"ABATE-TETO_(U$)_DA_GRATIFICACAO_NATALINA_(R$)" decimal(20,2) null,
	"ABATE-TETO_(U$)_DA_GRATIFICACAO_NATALINA_(U$)" decimal(20,2) null,
	"FERIAS_(R$)" decimal(20,2) null,
	"FERIAS_(U$)" decimal(20,2) null,
	"OUTRAS_REMUNERACOES_EVENTUAIS_(R$)" decimal(20,2) null,
	"OUTRAS_REMUNERACOES_EVENTUAIS_(U$)" decimal(20,2) null,
	"IRRF_(R$)" decimal(20,2) null,
	"IRRF_(U$)" decimal(20,2) null,
	"PSS/RPGS_(R$)" decimal(20,2) null,
	"PSS/RPGS_(U$)" decimal(20,2) null,
	"DEMAIS_DEDUCOES_(R$)" decimal(20,2) null,
	"DEMAIS_DEDUCOES_(U$)" decimal(20,2) null,
	"PENSAO_MILITAR_(R$)" decimal(20,2) null,
	"PENSAO_MILITAR_(U$)" decimal(20,2) null,
	"FUNDO_DE_SAUDE_(R$)" decimal(20,2) null,
	"FUNDO_DE_SAUDE_(U$)" decimal(20,2) null,
	"TAXA_DE_OCUPACAO_IMOVEL_FUNCIONAL_(R$)" decimal(20,2) null,
	"TAXA_DE_OCUPACAO_IMOVEL_FUNCIONAL_(U$)" decimal(20,2) null,
	"REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_(R$)" decimal(20,2) null,
	"REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_(U$)" decimal(20,2) null,
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_CIVIL_(R$)(*)" decimal(20,2) null,
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_CIVIL_(U$)(*)" decimal(20,2) null,
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_MILITAR_(R$)(*)" decimal(20,2) null,
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_MILITAR_(U$)(*)" decimal(20,2) null,
	"VERBAS_INDENIZATORIAS_P_DESLIGAMENTO_VOLUNTARIO_MP_792/2017_(R$)" decimal(20,2) null,
	"VERBAS_INDENIZATORIAS_P_DESLIGAMENTO_VOLUNTARIO_MP_792/2017_(U$)" decimal(20,2) null,
	"TOTAL_DE_VERBAS_INDENIZATORIAS_(R$)(*)" decimal(20,2) null,
	"TOTAL_DE_VERBAS_INDENIZATORIAS_(U$)(*)" decimal(20,2) null
);

insert into public."final_servidores_siape_remuneracao"(
	"ANO",
	"MES",
	"ID_SERVIDOR_PORTAL",
	"CPF",
	"NOME",
	"REMUNERACAO_BASICA_BRUTA_(R$)",
	"REMUNERACAO_BASICA_BRUTA_(U$)",
	"ABATE-TETO_(R$)",
	"ABATE-TETO_(U$)",
	"GRATIFICACAO_NATALINA_(R$)",
	"GRATIFICACAO_NATALINA_(U$)",
	"ABATE-TETO_(U$)_DA_GRATIFICACAO_NATALINA_(R$)",
	"ABATE-TETO_(U$)_DA_GRATIFICACAO_NATALINA_(U$)",
	"FERIAS_(R$)",
	"FERIAS_(U$)",
	"OUTRAS_REMUNERACOES_EVENTUAIS_(R$)",
	"OUTRAS_REMUNERACOES_EVENTUAIS_(U$)",
	"IRRF_(R$)",
	"IRRF_(U$)",
	"PSS/RPGS_(R$)",
	"PSS/RPGS_(U$)",
	"DEMAIS_DEDUCOES_(R$)",
	"DEMAIS_DEDUCOES_(U$)",
	"PENSAO_MILITAR_(R$)",
	"PENSAO_MILITAR_(U$)",
	"FUNDO_DE_SAUDE_(R$)",
	"FUNDO_DE_SAUDE_(U$)",
	"TAXA_DE_OCUPACAO_IMOVEL_FUNCIONAL_(R$)",
	"TAXA_DE_OCUPACAO_IMOVEL_FUNCIONAL_(U$)",
	"REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_(R$)",
	"REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_(U$)",
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_CIVIL_(R$)(*)",
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_CIVIL_(U$)(*)",
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_MILITAR_(R$)(*)",
	"VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_MILITAR_(U$)(*)",
	"VERBAS_INDENIZATORIAS_P_DESLIGAMENTO_VOLUNTARIO_MP_792/2017_(R$)",
	"VERBAS_INDENIZATORIAS_P_DESLIGAMENTO_VOLUNTARIO_MP_792/2017_(U$)",
	"TOTAL_DE_VERBAS_INDENIZATORIAS_(R$)(*)",
	"TOTAL_DE_VERBAS_INDENIZATORIAS_(U$)(*)"
)
select
	cast("ANO" as integer),
	cast("MES" as integer),
	"ID_SERVIDOR_PORTAL",
	"CPF",
	"NOME",
	cast(replace("REMUNERACAO_BASICA_BRUTA_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("REMUNERACAO_BASICA_BRUTA_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("ABATE-TETO_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("ABATE-TETO_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("GRATIFICACAO_NATALINA_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("GRATIFICACAO_NATALINA_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("ABATE-TETO_(U$)_DA_GRATIFICACAO_NATALINA_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("ABATE-TETO_(U$)_DA_GRATIFICACAO_NATALINA_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("FERIAS_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("FERIAS_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("OUTRAS_REMUNERACOES_EVENTUAIS_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("OUTRAS_REMUNERACOES_EVENTUAIS_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("IRRF_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("IRRF_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("PSS/RPGS_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("PSS/RPGS_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("DEMAIS_DEDUCOES_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("DEMAIS_DEDUCOES_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("PENSAO_MILITAR_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("PENSAO_MILITAR_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("FUNDO_DE_SAUDE_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("FUNDO_DE_SAUDE_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("TAXA_DE_OCUPACAO_IMOVEL_FUNCIONAL_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("TAXA_DE_OCUPACAO_IMOVEL_FUNCIONAL_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("REMUNERACAO_APOS_DEDUCOES_OBRIGATORIAS_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_CIVIL_(R$)(*)", ',', '.') as decimal(20,2)),
	cast(replace("VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_CIVIL_(U$)(*)", ',', '.') as decimal(20,2)),
	cast(replace("VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_MILITAR_(R$)(*)", ',', '.') as decimal(20,2)),
	cast(replace("VERBAS_INDENIZATORIAS_REGISTRADAS_EM_S_DE_PESSOAS_-_MILITAR_(U$)(*)", ',', '.') as decimal(20,2)),
	cast(replace("VERBAS_INDENIZATORIAS_P_DESLIGAMENTO_VOLUNTARIO_MP_792/2017_(R$)", ',', '.') as decimal(20,2)),
	cast(replace("VERBAS_INDENIZATORIAS_P_DESLIGAMENTO_VOLUNTARIO_MP_792/2017_(U$)", ',', '.') as decimal(20,2)),
	cast(replace("TOTAL_DE_VERBAS_INDENIZATORIAS_(R$)(*)", ',', '.') as decimal(20,2)),
	cast(replace("TOTAL_DE_VERBAS_INDENIZATORIAS_(U$)(*)", ',', '.') as decimal(20,2))
from public."tmp_servidores_siape_remuneracao";
